/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.firnanda.quiz2;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Firnanda(Rizka)
 */
public class Menu extends javax.swing.JFrame {
    private int id = 0;
    private String kode;
    private DefaultTableModel DtModel;
    private DefaultComboBoxModel DcModel;
    private ArrayList<Item> t = new ArrayList<>();
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
        NewBarang newbarang = new NewBarang();
        this.DcModel = new DefaultComboBoxModel<>(newbarang.getJenisNama().toArray());
        TableTransaksi tableModel = new TableTransaksi();
        this.DtModel = new DefaultTableModel(tableModel.getKolomNama(), 0);
        
        CodeText.setEnabled(false);
        AddButton.setEnabled(false);
        RemoveButton.setEnabled(false);
        ComboBoxItem.setEnabled(false);
        SaveButton.setEnabled(false);
        CancelButton.setEnabled(false);
        ItemText.setEnabled(false);
        TableNama.setEnabled(false);
        
    }
    
    private void incId(){
        this.id += 1;
    }
    
    private void decId(){
        this.id -= 1;
    }
    
    private Object[] addItem(String nama, int jumlah){
        float harga = 0;
        NewBarang items = new NewBarang();
        for(int i = 0 ; i < items.getHargaBarang().size(); i++){            
            if(nama.equalsIgnoreCase(items.getJenisNama().get(i))){
            harga = items.getHargaBarang().get(i);
            }
        }
        
        Object[] ob = {
            nama,
            harga,
            jumlah
        };
        return ob;
    }
    
    private void updateJumlah(String nama, int add){
        ArrayList<String> item = new ArrayList<>();
        for(int i = 0; i < DtModel.getRowCount(); i++){
            item.add(DtModel.getValueAt(i, 0).toString());
        }
        for(int i = 0; i < item.size(); i++){
            if(item.get(i).equals(nama)){
                int jumlah = new Integer (DtModel.getValueAt(i, 2).toString());
                DtModel.setValueAt(jumlah + add, i, 2);
            }
        }
    }
    
        private boolean Duplicate(String nama){
            boolean result = false;
            ArrayList<String> item = new ArrayList<>();
            for(int i = 0; i < DtModel.getRowCount(); i++){
                item.add(DtModel.getValueAt(i, 0).toString());
            }
            for(String i : item){
                if(i.equals (nama)){
                    result = true;
                }
            }
            return result;
        }
        
        boolean isEmpty(){
            return this.TableNama.getModel().getRowCount() <= 0;
        }
        
        private void belanja(){
            if(isEmpty()){
                this.SaveButton.setEnabled(false);
                this.RemoveButton.setEnabled(false);
            }else{
                this.SaveButton.setEnabled(true);
                this.RemoveButton.setEnabled(true);
            }
        }
        
        private void newTransaksi(){
            this.ItemText.setText("");
            this.CodeText.setText("");
            this.NewButton.setEnabled(true);
            this.SaveButton.setEnabled(false);
            this.CancelButton.setEnabled(false);
            this.AddButton.setEnabled(false);
            this.RemoveButton.setEnabled(false);
            this.ItemText.setEnabled(false);
            this.ComboBoxItem.setEnabled(false);
            this.DtModel.setRowCount(0);
            this.t.clear();
        }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CodeLabel = new javax.swing.JLabel();
        ItemLabel = new javax.swing.JLabel();
        CodeText = new javax.swing.JTextField();
        ComboBoxItem = new javax.swing.JComboBox<>();
        ItemText = new javax.swing.JTextField();
        NewButton = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableNama = new javax.swing.JTable();
        SaveButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        RemoveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CodeLabel.setText("Code");

        ItemLabel.setText("Items");

        CodeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodeTextActionPerformed(evt);
            }
        });

        ItemText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemTextActionPerformed(evt);
            }
        });

        NewButton.setText("New");
        NewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewButtonActionPerformed(evt);
            }
        });

        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        TableNama.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Harga", "Jumlah"
            }
        ));
        jScrollPane1.setViewportView(TableNama);

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        RemoveButton.setText("Remove");
        RemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CodeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(CodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ItemLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SaveButton)
                                .addGap(35, 35, 35)
                                .addComponent(CancelButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ComboBoxItem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ItemText, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RemoveButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(AddButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NewButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodeLabel)
                    .addComponent(CodeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ItemLabel)
                    .addComponent(ComboBoxItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ItemText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RemoveButton)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelButton)
                    .addComponent(SaveButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewButtonActionPerformed
        // TODO add your handling code here:
        
        AddButton.setEnabled(true);
        CancelButton.setEnabled(true);
        RemoveButton.setEnabled(true);
        SaveButton.setEnabled(true);
        ComboBoxItem.setEnabled(true);
        ItemText.setEnabled(true);
        NewButton.setEnabled(false);
        
        int i = 0;
        i++;
        
        Date d = new Date();
        SimpleDateFormat SDFormat = new SimpleDateFormat("yyMMdd");
        String dateString = SDFormat.format(d);
        
        CodeText.setText(dateString + "0" + i);
    }//GEN-LAST:event_NewButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:
        try{
            for(int i = 0; i < DtModel.getColumnCount(); i++){
                String nama = DtModel.getValueAt(i, 0).toString();
                float harga = new Float(DtModel.getValueAt(i, 1).toString());
                int jumlah = new Integer(DtModel.getValueAt(i, 2).toString());
                this.t.add(new Item(nama, harga, jumlah));
            }
            Transaksi transaksi = new Transaksi(this.kode, this.t);
            StringBuilder sbr = new StringBuilder();
            sbr.append(transaksi.Pembayaran());
            JOptionPane.showMessageDialog(this, sbr, "Transaksi", JOptionPane.INFORMATION_MESSAGE);
            newTransaksi();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void ItemTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemTextActionPerformed

    private void CodeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodeTextActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        String nama = this.ComboBoxItem.getSelectedItem().toString();
        int jumlah = new Integer(this.ItemText.getText());
        if(Duplicate(nama)){
            updateJumlah(nama, jumlah);
        }else{
            DtModel.addRow(addItem(nama, jumlah));
        }
        this.belanja();
    }//GEN-LAST:event_AddButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        newTransaksi();
        this.decId();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void RemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemoveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel CodeLabel;
    private javax.swing.JTextField CodeText;
    private javax.swing.JComboBox<String> ComboBoxItem;
    private javax.swing.JLabel ItemLabel;
    private javax.swing.JTextField ItemText;
    private javax.swing.JButton NewButton;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JTable TableNama;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
